<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models2\**" />
    <Compile Remove="wwwroot\alpine\**" />
    <Compile Remove="wwwroot\Ecomus\**" />
    <Compile Remove="wwwroot\fables\**" />
    <Content Remove="Models2\**" />
    <Content Remove="wwwroot\alpine\**" />
    <Content Remove="wwwroot\Ecomus\**" />
    <Content Remove="wwwroot\fables\**" />
    <EmbeddedResource Remove="Models2\**" />
    <EmbeddedResource Remove="wwwroot\alpine\**" />
    <EmbeddedResource Remove="wwwroot\Ecomus\**" />
    <EmbeddedResource Remove="wwwroot\fables\**" />
    <None Remove="Models2\**" />
    <None Remove="wwwroot\alpine\**" />
    <None Remove="wwwroot\Ecomus\**" />
    <None Remove="wwwroot\fables\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\fontawesome\.gitignore" />
    <None Include="wwwroot\css\fontawesome\.npmignore" />
    <None Include="wwwroot\css\fontawesome\css\font-awesome.css.map" />
    <None Include="wwwroot\css\fontawesome\fonts\fontawesome-webfont.svg" />
    <None Include="wwwroot\css\fontawesome\fonts\fontawesome-webfont.woff2" />
    <None Include="wwwroot\css\fontawesome\less\animated.less" />
    <None Include="wwwroot\css\fontawesome\less\bordered-pulled.less" />
    <None Include="wwwroot\css\fontawesome\less\core.less" />
    <None Include="wwwroot\css\fontawesome\less\fixed-width.less" />
    <None Include="wwwroot\css\fontawesome\less\font-awesome.less" />
    <None Include="wwwroot\css\fontawesome\less\icons.less" />
    <None Include="wwwroot\css\fontawesome\less\larger.less" />
    <None Include="wwwroot\css\fontawesome\less\list.less" />
    <None Include="wwwroot\css\fontawesome\less\mixins.less" />
    <None Include="wwwroot\css\fontawesome\less\path.less" />
    <None Include="wwwroot\css\fontawesome\less\rotated-flipped.less" />
    <None Include="wwwroot\css\fontawesome\less\stacked.less" />
    <None Include="wwwroot\css\fontawesome\less\variables.less" />
    <None Include="wwwroot\css\fontawesome\scss\font-awesome.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_animated.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_bordered-pulled.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_core.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_fixed-width.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_icons.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_larger.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_list.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_mixins.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_path.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_rotated-flipped.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_stacked.scss" />
    <None Include="wwwroot\css\fontawesome\scss\_variables.scss" />
    <None Include="wwwroot\fonts\icomoon.eot%40ifrjc8" />
    <None Include="wwwroot\fonts\icomoon.svg%40ifrjc8" />
    <None Include="wwwroot\fonts\icomoon.ttf%40ifrjc8" />
    <None Include="wwwroot\fonts\icomoon.woff%40ifrjc8" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
