// <auto-generated />
using System;
using Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.ActualizacionPrecio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdMarca")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("PorcentajeImporte")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PrecioLista")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Talledesde")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("talledesde");

                    b.Property<string>("Tallehasta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tallehasta");

                    b.HasKey("Id");

                    b.HasIndex("IdMarca");

                    b.ToTable("ActualizacionPrecio");
                });

            modelBuilder.Entity("Api.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Banco", (string)null);
                });

            modelBuilder.Entity("Api.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Caja", (string)null);
                });

            modelBuilder.Entity("Api.Models.CajaMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMovimientoCaja")
                        .HasColumnType("int");

                    b.Property<long>("IdVendedor")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdTipoMovimientoCaja");

                    b.HasIndex("IdVendedor");

                    b.ToTable("CajaMovimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.Carrito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<long?>("IdEstadoCarrito")
                        .HasColumnType("bigint");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdEstadoCarrito");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("Api.Models.CarritoProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("IdCarrito")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdProducto");

                    b.ToTable("CarritoProducto", (string)null);
                });

            modelBuilder.Entity("Api.Models.Cheque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("EsPropio")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCobro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdBanco")
                        .HasColumnType("int");

                    b.Property<long?>("IdPago")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ImporteCheque")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sucursal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdBanco");

                    b.ToTable("Cheque", (string)null);
                });

            modelBuilder.Entity("Api.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Calle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodCliente")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("cod_cliente")
                        .IsFixedLength();

                    b.Property<string>("Cuit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Depto")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("IdCondicionIva")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<int?>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefonoMovil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Torre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCondicionIva");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Api.Models.ClienteCuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoCuentaCorriente")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaUltimoPago")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("Id")
                        .HasName("PK__ClienteC__3214EC07613E6B20");

                    b.ToTable("ClienteCuentaCorriente", (string)null);
                });

            modelBuilder.Entity("Api.Models.ClienteCuentaCorrienteMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Debe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Haber")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IdClienteCuentaCorriente")
                        .HasColumnType("int");

                    b.Property<int?>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoMovimiento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Vencimiento")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__ClienteC__3214EC07ADAAEA3C");

                    b.HasIndex("IdClienteCuentaCorriente");

                    b.HasIndex("IdComprobante");

                    b.ToTable("ClienteCuentaCorrienteMovimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.Color", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("Api.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroEmisor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Cuit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("FechaVencimientoCae")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FechaVencimientoCAE");

                    b.Property<bool?>("Garantia")
                        .HasColumnType("bit");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdComprobanteReferencia")
                        .HasColumnType("int");

                    b.Property<long?>("IdMovimiento")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTarjeta")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTipoComprobante")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImporteNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IvaTasa1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Iva_Tasa1");

                    b.Property<decimal>("IvaTasa2")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Iva_Tasa2");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<bool?>("Nc")
                        .HasColumnType("bit")
                        .HasColumnName("NC");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCae")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NumeroCAE");

                    b.Property<decimal>("PercepcionIibb")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Percepcion_IIBB");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("Recargos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Comproba__3214EC07094B6776");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMovimiento");

                    b.HasIndex("IdTipoComprobante");

                    b.ToTable("Comprobante", (string)null);
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Descuentos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<long?>("IdCaja")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMovimiento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProveedor")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTipoComprobante")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImporteNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IvaTasa1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IvaTasa_1");

                    b.Property<decimal>("IvaTasa2")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IvaTasa_2");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("OtrosImpuestos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PercepcionIibb")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Percepcion_IIBB");

                    b.Property<string>("PuntoVenta")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_FacturaCompra");

                    b.HasIndex("IdMovimiento");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipoComprobante");

                    b.ToTable("ComprobanteCompra", (string)null);
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompraDescuento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("IdComprobanteCompra")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id")
                        .HasName("PK_FacturaCompraDescuento");

                    b.HasIndex("IdComprobanteCompra");

                    b.ToTable("ComprobanteCompraDescuento", (string)null);
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<long>("IdComprobanteCompra")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImpuestoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalItem")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprobanteCompra");

                    b.ToTable("ComprobanteCompraItem", (string)null);
                });

            modelBuilder.Entity("Api.Models.ComprobanteItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Bonificacion")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<long?>("IdComprobanteItemNc")
                        .HasColumnType("bigint")
                        .HasColumnName("IdComprobanteItemNC");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImpuestoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("Nc")
                        .HasColumnType("bit")
                        .HasColumnName("NC");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalItem")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdProducto");

                    b.ToTable("ComprobanteItem", (string)null);
                });

            modelBuilder.Entity("Api.Models.CondicionIva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Condicio__3214EC079E0B9F5A");

                    b.ToTable("CondicionIva", (string)null);
                });

            modelBuilder.Entity("Api.Models.Credito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<int>("Cuotas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEstadoCredito")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoCredito");

                    b.ToTable("Credito", (string)null);
                });

            modelBuilder.Entity("Api.Models.CuotaCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amortizacion")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<long>("IdCredito")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("InteresMora")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalCuota")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("TotalPago")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCredito");

                    b.ToTable("CuotaCredito", (string)null);
                });

            modelBuilder.Entity("Api.Models.Deposito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Deposito", (string)null);
                });

            modelBuilder.Entity("Api.Models.EstadoCarrito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EstadoCarrito", (string)null);
                });

            modelBuilder.Entity("Api.Models.EstadoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoCredito", (string)null);
                });

            modelBuilder.Entity("Api.Models.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FormaPago", (string)null);
                });

            modelBuilder.Entity("Api.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Alicuota")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Impuesto__3214EC0726ECC11F");

                    b.ToTable("Impuesto", (string)null);
                });

            modelBuilder.Entity("Api.Models.Iva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Descripcion")
                        .HasColumnType("numeric(5, 2)");

                    b.HasKey("Id");

                    b.ToTable("Iva", (string)null);
                });

            modelBuilder.Entity("Api.Models.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Api.Models.Movimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdSucursalEgreso")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSucursalIngreso")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTipoMovimiento")
                        .HasColumnType("bigint");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_Producto_TipoMovimiento");

                    b.HasIndex("IdTipoMovimiento");

                    b.ToTable("Movimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.NhibernateTest", b =>
                {
                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.ToTable("NHibernateTest", (string)null);
                });

            modelBuilder.Entity("Api.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCobroCheque")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdClienteCuentaCorrienteMovimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdTarjeta")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportePago")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroCheque")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroCupon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroTarjeta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdClienteCuentaCorrienteMovimiento");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdTarjeta");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("Api.Models.PreciosTable", b =>
                {
                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Costo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Precio")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PrecioSinIva")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.ToTable("PreciosTable", (string)null);
                });

            modelBuilder.Entity("Api.Models.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool?>("Carrito")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("IdColor")
                        .HasColumnType("bigint");

                    b.Property<long>("IdImpuesto")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTalle")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money");

                    b.Property<decimal>("PrecioSinIva")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdColor");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdTalle");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Api.Models.Producto2", b =>
                {
                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("IdColor")
                        .HasColumnType("bigint");

                    b.Property<long>("IdImpuesto")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTalle")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money");

                    b.Property<decimal>("PrecioSinIva")
                        .HasColumnType("money");

                    b.ToTable("Producto2", (string)null);
                });

            modelBuilder.Entity("Api.Models.ProductoImagen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<string>("LinkImagen")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoImagen", (string)null);
                });

            modelBuilder.Entity("Api.Models.ProductoMovimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<long>("IdMovimiento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdMovimiento");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoMovimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.ProductoStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Cantidad")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSucursal")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("ProductoStock", (string)null);
                });

            modelBuilder.Entity("Api.Models.Proveedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Calle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cuit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Depto")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<int?>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefonoMovil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Torre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Api.Models.ProveedorCuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoCuentaCorriente")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3214EC073948E8D8");

                    b.ToTable("ProveedorCuentaCorriente", (string)null);
                });

            modelBuilder.Entity("Api.Models.ProveedorCuentaCorrienteMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Debe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Haber")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedorCuentaCorriente")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoMovimiento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Vencimiento")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3214EC07F4CC4698");

                    b.ToTable("ProveedorCuentaCorrienteMovimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Api.Models.Sucursal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Coneccion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("EsCorriente")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MailPassword")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PathDownloads")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PathPrecios")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PathRemitos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Sucursal_1");

                    b.ToTable("Sucursal", (string)null);
                });

            modelBuilder.Entity("Api.Models.Talle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Modelo");

                    b.ToTable("Talle", (string)null);
                });

            modelBuilder.Entity("Api.Models.TalleCentral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Modelo_");

                    b.ToTable("TalleCentral", (string)null);
                });

            modelBuilder.Entity("Api.Models.Tarjetum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cuit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExpirationTime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FechaInicioActividades")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int");

                    b.Property<long?>("IdCondicionIva")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("PassCert")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PathCertificado")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PathImagen")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PuntoVenta")
                        .HasColumnType("int");

                    b.Property<string>("Sign")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Test")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_TarjetaCredito");

                    b.HasIndex("IdBanco");

                    b.ToTable("Tarjetum");
                });

            modelBuilder.Entity("Api.Models.TipoComprobante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("EsFiscal")
                        .HasColumnType("bit");

                    b.Property<string>("Letra")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("Signo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TipoComp__3214EC07790560BE");

                    b.ToTable("TipoComprobante", (string)null);
                });

            modelBuilder.Entity("Api.Models.TipoMovimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Manual")
                        .HasColumnType("bit");

                    b.Property<int?>("Signo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Movimiento");

                    b.ToTable("TipoMovimiento", (string)null);
                });

            modelBuilder.Entity("Api.Models.TipoMovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Signo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimientoCaja", (string)null);
                });

            modelBuilder.Entity("Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApeyNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Api.Models.Vendedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<long?>("IdSucursal")
                        .HasColumnType("bigint");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("Api.Models.ActualizacionPrecio", b =>
                {
                    b.HasOne("Api.Models.Marca", "IdMarcaNavigation")
                        .WithMany("ActualizacionPrecios")
                        .HasForeignKey("IdMarca")
                        .HasConstraintName("FK_ActualizacionPrecios_Marca");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("Api.Models.CajaMovimiento", b =>
                {
                    b.HasOne("Api.Models.Caja", "IdCajaNavigation")
                        .WithMany("CajaMovimientos")
                        .HasForeignKey("IdCaja")
                        .IsRequired()
                        .HasConstraintName("FK_CajaMovimiento_Caja");

                    b.HasOne("Api.Models.TipoMovimientoCaja", "IdTipoMovimientoCajaNavigation")
                        .WithMany("CajaMovimientos")
                        .HasForeignKey("IdTipoMovimientoCaja")
                        .IsRequired()
                        .HasConstraintName("FK_CajaMovimiento_TipoMovimientoCaja");

                    b.HasOne("Api.Models.Vendedor", "IdVendedorNavigation")
                        .WithMany("CajaMovimientos")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK_CajaMovimiento_Vendedor");

                    b.Navigation("IdCajaNavigation");

                    b.Navigation("IdTipoMovimientoCajaNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("Api.Models.Carrito", b =>
                {
                    b.HasOne("Api.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_Carrito_Cliente");

                    b.HasOne("Api.Models.Comprobante", "IdComprobanteNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdComprobante")
                        .HasConstraintName("FK_Carrito_Comprobante");

                    b.HasOne("Api.Models.EstadoCarrito", "IdEstadoCarritoNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdEstadoCarrito")
                        .HasConstraintName("FK_Carrito_EstadoCarrito");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdComprobanteNavigation");

                    b.Navigation("IdEstadoCarritoNavigation");
                });

            modelBuilder.Entity("Api.Models.CarritoProducto", b =>
                {
                    b.HasOne("Api.Models.Carrito", "IdCarritoNavigation")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdCarrito")
                        .IsRequired()
                        .HasConstraintName("FK_CarritoProducto_Carrito");

                    b.HasOne("Api.Models.Producto", "IdProductoNavigation")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_CarritoProducto_Producto");

                    b.Navigation("IdCarritoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Api.Models.Cheque", b =>
                {
                    b.HasOne("Api.Models.Banco", "IdBancoNavigation")
                        .WithMany("Cheques")
                        .HasForeignKey("IdBanco")
                        .HasConstraintName("FK_Cheque_Banco");

                    b.Navigation("IdBancoNavigation");
                });

            modelBuilder.Entity("Api.Models.Cliente", b =>
                {
                    b.HasOne("Api.Models.CondicionIva", "IdCondicionIvaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdCondicionIva")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_CondicionIva");

                    b.Navigation("IdCondicionIvaNavigation");
                });

            modelBuilder.Entity("Api.Models.ClienteCuentaCorrienteMovimiento", b =>
                {
                    b.HasOne("Api.Models.ClienteCuentaCorriente", "IdClienteCuentaCorrienteNavigation")
                        .WithMany("ClienteCuentaCorrienteMovimientos")
                        .HasForeignKey("IdClienteCuentaCorriente")
                        .IsRequired()
                        .HasConstraintName("FK_ClienteCuentaCorrienteMovimiento_ClienteCuentaCorriente");

                    b.HasOne("Api.Models.Comprobante", "IdComprobanteNavigation")
                        .WithMany("ClienteCuentaCorrienteMovimientos")
                        .HasForeignKey("IdComprobante")
                        .HasConstraintName("FK_ClienteCuentaCorrienteMovimiento_Comprobante");

                    b.Navigation("IdClienteCuentaCorrienteNavigation");

                    b.Navigation("IdComprobanteNavigation");
                });

            modelBuilder.Entity("Api.Models.Comprobante", b =>
                {
                    b.HasOne("Api.Models.Caja", "IdCajaNavigation")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdCaja")
                        .HasConstraintName("FK_Comprobante_Caja");

                    b.HasOne("Api.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Comprobante_Cliente");

                    b.HasOne("Api.Models.Movimiento", "IdMovimientoNavigation")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdMovimiento")
                        .HasConstraintName("FK_Comprobante_Movimiento");

                    b.HasOne("Api.Models.TipoComprobante", "IdTipoComprobanteNavigation")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdTipoComprobante")
                        .IsRequired()
                        .HasConstraintName("FK_Comprobante_TipoComprobante");

                    b.Navigation("IdCajaNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdMovimientoNavigation");

                    b.Navigation("IdTipoComprobanteNavigation");
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompra", b =>
                {
                    b.HasOne("Api.Models.Movimiento", "IdMovimientoNavigation")
                        .WithMany("ComprobanteCompras")
                        .HasForeignKey("IdMovimiento")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaCompra_Movimiento");

                    b.HasOne("Api.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("ComprobanteCompras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteCompra_Proveedor");

                    b.HasOne("Api.Models.TipoComprobante", "IdTipoComprobanteNavigation")
                        .WithMany("ComprobanteCompras")
                        .HasForeignKey("IdTipoComprobante")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteCompra_TipoComprobante");

                    b.Navigation("IdMovimientoNavigation");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdTipoComprobanteNavigation");
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompraDescuento", b =>
                {
                    b.HasOne("Api.Models.ComprobanteCompra", "IdComprobanteCompraNavigation")
                        .WithMany("ComprobanteCompraDescuentos")
                        .HasForeignKey("IdComprobanteCompra")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaCompraDescuento_FacturaCompra");

                    b.Navigation("IdComprobanteCompraNavigation");
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompraItem", b =>
                {
                    b.HasOne("Api.Models.ComprobanteCompra", "IdComprobanteCompraNavigation")
                        .WithMany("ComprobanteCompraItems")
                        .HasForeignKey("IdComprobanteCompra")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteCompraItem_ComprobanteCompra");

                    b.Navigation("IdComprobanteCompraNavigation");
                });

            modelBuilder.Entity("Api.Models.ComprobanteItem", b =>
                {
                    b.HasOne("Api.Models.Comprobante", "IdComprobanteNavigation")
                        .WithMany("ComprobanteItems")
                        .HasForeignKey("IdComprobante")
                        .HasConstraintName("FK_ComprobanteItem_Comprobante");

                    b.HasOne("Api.Models.Producto", "IdProductoNavigation")
                        .WithMany("ComprobanteItems")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteItem_Producto");

                    b.Navigation("IdComprobanteNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Api.Models.Credito", b =>
                {
                    b.HasOne("Api.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Creditos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Credito_Cliente");

                    b.HasOne("Api.Models.EstadoCredito", "IdEstadoCreditoNavigation")
                        .WithMany("Creditos")
                        .HasForeignKey("IdEstadoCredito")
                        .IsRequired()
                        .HasConstraintName("FK_Credito_EstadoCredito");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoCreditoNavigation");
                });

            modelBuilder.Entity("Api.Models.CuotaCredito", b =>
                {
                    b.HasOne("Api.Models.Credito", "IdCreditoNavigation")
                        .WithMany("CuotaCreditos")
                        .HasForeignKey("IdCredito")
                        .IsRequired()
                        .HasConstraintName("FK_CuotaCredito_Credito");

                    b.Navigation("IdCreditoNavigation");
                });

            modelBuilder.Entity("Api.Models.Movimiento", b =>
                {
                    b.HasOne("Api.Models.TipoMovimiento", "IdTipoMovimientoNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdTipoMovimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_TipoMovimiento");

                    b.Navigation("IdTipoMovimientoNavigation");
                });

            modelBuilder.Entity("Api.Models.Pago", b =>
                {
                    b.HasOne("Api.Models.Caja", "IdCajaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCaja")
                        .HasConstraintName("FK_Pago_Caja");

                    b.HasOne("Api.Models.ClienteCuentaCorrienteMovimiento", "IdClienteCuentaCorrienteMovimientoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdClienteCuentaCorrienteMovimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Pago_ClienteCuentaCorrienteMovimiento");

                    b.HasOne("Api.Models.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_Pago_FormaPago");

                    b.HasOne("Api.Models.Tarjetum", "IdTarjetaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdTarjeta")
                        .HasConstraintName("FK_Pago_TarjetaCredito");

                    b.Navigation("IdCajaNavigation");

                    b.Navigation("IdClienteCuentaCorrienteMovimientoNavigation");

                    b.Navigation("IdFormaPagoNavigation");

                    b.Navigation("IdTarjetaNavigation");
                });

            modelBuilder.Entity("Api.Models.Producto", b =>
                {
                    b.HasOne("Api.Models.Color", "IdColorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdColor")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Color");

                    b.HasOne("Api.Models.Marca", "IdMarcaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Marca");

                    b.HasOne("Api.Models.Talle", "IdTalleNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdTalle")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Talle");

                    b.Navigation("IdColorNavigation");

                    b.Navigation("IdMarcaNavigation");

                    b.Navigation("IdTalleNavigation");
                });

            modelBuilder.Entity("Api.Models.ProductoImagen", b =>
                {
                    b.HasOne("Api.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoImagens")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoImagen_Producto");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Api.Models.ProductoMovimiento", b =>
                {
                    b.HasOne("Api.Models.Movimiento", "IdMovimientoNavigation")
                        .WithMany("ProductoMovimientos")
                        .HasForeignKey("IdMovimiento")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoMovimiento_Movimiento");

                    b.HasOne("Api.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoMovimientos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoMovimiento_Producto");

                    b.Navigation("IdMovimientoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Api.Models.ProductoStock", b =>
                {
                    b.HasOne("Api.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoStocks")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoStock_Producto");

                    b.HasOne("Api.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("ProductoStocks")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoStock_Sucursal");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("Api.Models.Tarjetum", b =>
                {
                    b.HasOne("Api.Models.Banco", "IdBancoNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("IdBanco")
                        .IsRequired()
                        .HasConstraintName("FK_TarjetaCredito_Banco");

                    b.Navigation("IdBancoNavigation");
                });

            modelBuilder.Entity("Api.Models.Vendedor", b =>
                {
                    b.HasOne("Api.Models.Rol", "IdRolNavigation")
                        .WithMany("Vendedors")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK_Vendedor_Rol");

                    b.HasOne("Api.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("Vendedors")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK_Vendedor_Sucursal");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("Api.Models.Banco", b =>
                {
                    b.Navigation("Cheques");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Api.Models.Caja", b =>
                {
                    b.Navigation("CajaMovimientos");

                    b.Navigation("Comprobantes");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Models.Carrito", b =>
                {
                    b.Navigation("CarritoProductos");
                });

            modelBuilder.Entity("Api.Models.Cliente", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Comprobantes");

                    b.Navigation("Creditos");
                });

            modelBuilder.Entity("Api.Models.ClienteCuentaCorriente", b =>
                {
                    b.Navigation("ClienteCuentaCorrienteMovimientos");
                });

            modelBuilder.Entity("Api.Models.ClienteCuentaCorrienteMovimiento", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Models.Color", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Api.Models.Comprobante", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("ClienteCuentaCorrienteMovimientos");

                    b.Navigation("ComprobanteItems");
                });

            modelBuilder.Entity("Api.Models.ComprobanteCompra", b =>
                {
                    b.Navigation("ComprobanteCompraDescuentos");

                    b.Navigation("ComprobanteCompraItems");
                });

            modelBuilder.Entity("Api.Models.CondicionIva", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Api.Models.Credito", b =>
                {
                    b.Navigation("CuotaCreditos");
                });

            modelBuilder.Entity("Api.Models.EstadoCarrito", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("Api.Models.EstadoCredito", b =>
                {
                    b.Navigation("Creditos");
                });

            modelBuilder.Entity("Api.Models.FormaPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Models.Marca", b =>
                {
                    b.Navigation("ActualizacionPrecios");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Api.Models.Movimiento", b =>
                {
                    b.Navigation("ComprobanteCompras");

                    b.Navigation("Comprobantes");

                    b.Navigation("ProductoMovimientos");
                });

            modelBuilder.Entity("Api.Models.Producto", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("ComprobanteItems");

                    b.Navigation("ProductoImagens");

                    b.Navigation("ProductoMovimientos");

                    b.Navigation("ProductoStocks");
                });

            modelBuilder.Entity("Api.Models.Proveedor", b =>
                {
                    b.Navigation("ComprobanteCompras");
                });

            modelBuilder.Entity("Api.Models.Rol", b =>
                {
                    b.Navigation("Vendedors");
                });

            modelBuilder.Entity("Api.Models.Sucursal", b =>
                {
                    b.Navigation("ProductoStocks");

                    b.Navigation("Vendedors");
                });

            modelBuilder.Entity("Api.Models.Talle", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Api.Models.Tarjetum", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Models.TipoComprobante", b =>
                {
                    b.Navigation("ComprobanteCompras");

                    b.Navigation("Comprobantes");
                });

            modelBuilder.Entity("Api.Models.TipoMovimiento", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Api.Models.TipoMovimientoCaja", b =>
                {
                    b.Navigation("CajaMovimientos");
                });

            modelBuilder.Entity("Api.Models.Vendedor", b =>
                {
                    b.Navigation("CajaMovimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
